# Generated by Django 2.2.1 on 2019-11-07 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('gender', models.IntegerField(choices=[('0', '男'), ('1', '女')], verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
            ],
            options={
                'verbose_name_plural': '作者',
                'verbose_name': '作者',
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='类型')),
                ('descriptions', models.TextField(verbose_name='描述')),
            ],
            options={
                'verbose_name_plural': '类型',
                'verbose_name': '类型',
                'db_table': 'type',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('date', models.DateField(auto_now=True, verbose_name='日期')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('description', models.TextField(verbose_name='描述')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Article.Author')),
                ('type', models.ManyToManyField(to='Article.Type')),
            ],
            options={
                'verbose_name_plural': '作者',
                'verbose_name': '作者',
                'db_table': 'article',
            },
        ),
    ]
