# Generated by Django 2.2.1 on 2019-11-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0002_auto_20191108_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='picture',
            field=models.ImageField(default='images/02.jpg', upload_to='images', verbose_name='图片'),
        ),
    ]
