# Generated by Django 2.2.1 on 2019-11-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0004_auto_20191108_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='click',
            field=models.IntegerField(default=0, verbose_name='点击率'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='recommend',
            field=models.IntegerField(choices=[(0, '不推荐'), (1, '推荐')], default=0, verbose_name='推荐'),
        ),
    ]
